name = "slm-libgit2"
version = "0.0.5"

[dependencies]

[dependencies.libgit2]
pkg="libgit2"
version="1.8.1"
type="conan"
options.shared = "False"
options.threadsafe = "True"
options.with_libssh2 = "True"
options.with_regex = "builtin"
options.with_http_parser = "http-parser"
options.linux.fPIC = "True"
options.linux.with_https = "openssl"
options.linux.with_ntlmclient = "False"
options.linux.with_sha1 = "openssl"
options.macos.fPIC = "True"
options.macos.with_https = "security"
options.macos.with_iconv = "False"
options.macos.with_ntlmclient = "False"
options.macos.with_sha1 = "commoncrypto"
options.windows.with_https = "winhttp"
options.windows.with_sha1 = "win32"
